version: '3'
services:
  app:
    container_name: node-app
    build: .
    depends_on:
      - postgres_db
    env_file: .env
    command: npm run dev
    ports:
      - '3000:3000'
    volumes:
      - .:/chotuve

  postgres_db:
    container_name: postgres-db
    image: postgres:12.2
    ports:
      - '35432:5432'
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - database-data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: dbtest

volumes:
  database-data:
