version: '3'
services:
  app:
    container_name: node-app
    build:
      context: .
    depends_on:
      - postgres_db
    env_file: .env
    command: npm run test
    #    command: npm run dev
    ports:
      - '3000:3000'
    volumes:
      - .:/chotuve
    links:
      - postgres_db

  postgres_db:
    container_name: postgres-db
    build:
      context: ./db
      dockerfile: Dockerfile
    image: postgres:12.2
    ports:
      - '35432:5432'
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db
